version: '3.3'

services:
   portainer:
     image: portainer/portainer:latest
     volumes:
       - data:/data
       - /var/run/docker.sock:/var/run/docker.sock
     ports:
       - "9000:9000"
     restart: always
     environment:
       GIT_BUCKET_VERSION: 4.31.2
       PREFIX: git

volumes:
    data: {}
