name: Sphinx HTML generatie

on:
  push:
    branches: 
      - 'master'
#     paths:
#     - '!docs/**'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate HTML
      run: |
        sphinx-build -M html source/ build/
    - name: Update docs/
      run: |
        rm -rf docs/
        mv build/html docs/
        rm -rf build/
        touch docs/.nojekyll
    - name: push
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish'
        force-add: 'true'
